#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr
picom -f &
xrandr -r 144.00
sh ~/.config/polybar/nord-bspwm/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Alacritty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a "zoom " desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a code-oss desktop='^7'
bspc rule -a Thunar desktop='^8'
bspc rule -a Gimp desktop='^9'
